version: "3"
services:
  app:
    build: .
    links:
      - mysql
      - mongo
    ports:
      - "5000:5000"
    command: python -u reviews.py
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: AMAZON
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: password
      # Password for root access
    volumes:
      - /var/lib/mysql
  mongo:
    image: mongo:latest
    volumes:
      - /var/lib/mongodb
    ports:
      - "4545:27017"
