version: "3"
services:
        backend:
                image: 277965450838.dkr.ecr.ap-southeast-1.amazonaws.com/database-project-backend
                ports:
                        - ${REST_PORT}:${REST_PORT}
                        - ${MYSQL_PORT}:${MYSQL_PORT}
                        - ${MONGODB_PORT}:${MONGODB_PORT}
                command: python3 -m flask run --host=0.0.0.0 --port=${REST_PORT}
        frontend:
                image: 277965450838.dkr.ecr.ap-southeast-1.amazonaws.com/database-project-frontend
                ports:
                        - ${VUEJS_PORT}:${VUEJS_PORT}
