version: "3"
services:
  app:
    build: .
    links:
      - mysql
      - mongo
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    command: python -u reviews.py
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: AMAZON
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: password
      # Password for root access
    volumes:
      - ./sql-dump:/docker-entrypoint-initdb.d
  mongo:
    image: mongo:3.6.3
    volumes:
      - ./mongo-seed:/mongo-seed
    # command:
    #   /mongo-seed/import.sh
    # ports:
    #   - "43440:27017"
    # environment:
    #   CONN_NAME: test
    #   DB_HOST: mongo
    #   DB_PORT: 43440
