version: "3.7"
services:
        backend:
                build: ./backend
                expose:
                        - ${REST_PORT}
                        - ${MYSQL_PORT}
                        - ${MONGODB_PORT}
                ports:
                        - ${REST_PORT}:${REST_PORT}
                        - ${MYSQL_PORT}:${MYSQL_PORT}
                        - ${MONGODB_PORT}:${MONGODB_PORT}
                command: python3 -m flask run --host=0.0.0.0 --port=${REST_PORT}
        frontend:
                build: ./frontend/ebook
                expose:
                        - ${VUEJS_PORT}
                ports:
                        - ${VUEJS_PORT}:${VUEJS_PORT}
                command: ["nginx", "-g", "daemon off;"]
