version: "3"
services:
  app:
    build: .
    links:
      - mysql
      - mongo
    ports:
      - "5000:5000"
    command: python -u reviews.py
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: ''
      MYSQL_RANDOM_ROOT_PASSWORD: 'password'
      # Password for root access
    volumes:
      - /var/lib/mysql
  mongo:
    image: mongo:latest
    volumes:
      - /data/db
    ports:
      - "4545:27017"
