version: "3"
services:
  app:
    build: .
    links:
      - mysql
      - mongodb
    ports:
      - "5000:5000"
    command: flask run
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: ''
      MYSQL_RANDOM_ROOT_PASSWORD: 'password'
      # Password for root access
    volumes:
      - /var/lib/mysql
  mongodb:
    image: mongo:3.0.2
    ports:
      - "32001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    # volumes:
    #   - mongodbdata:/data/db
